### ISSUE TITLE
Figure out how to reference a dependency's jar path in an SBT config

### ISSUE THREAD

**Issue by non** [non/clouseau#3]
Right now, users can write:

```scala
libraryDependencies += "org.spire-math" %% "clouseau" % "0.1.0"
```

But it doesn't do them any good, since what they need to *use* Clouseau is:

```scala
javaOptions += "-javaagent:path/to/clouseau.jar"

fork := true
```

That path is likely to end up being something like:

```
$HOME/.ivy2/cache/org.spire-math/clouseau_2.12/jars/clouseau_2.12-0.1.0.jar
```

It would be great if there was a way for users to use a function to configure their `-javaagent` to be wherever Clouseau ends up, e.g. something like:

```scala
val clouseau = "org.spire-math" %% "clouseau" % "0.1.0"

libraryDependencies += clouseau

javaOptions += ("-javaagent:" + pathOf(clouseau))
```

I haven't been able to figure out how to do this, or if it's possible.

**Comment by fommil** [comment]
Have a look in ensime-sbt file EnsimePlugin.scala for lots of ways to access the ivy classifiers. You can almost certainly iterate the list and narrow by name, extracting the jar path.

Or, much simpler, if you just want the jar and don't care about integrations, look in CoursierHelper for how we resolve ensime-server jars. You could define an intransitive dependency and run the same code.

**Comment by fommil** [comment]
Oh, using this for a java agent is a good idea. Yeah the CoursierHelper approach will almost certainly work, but will add coursier as a dep to the user's build. There is also a new libraryManagement API in sbt, but I haven't looked.

Probably a helper method addJavaAgent would be handy. I'd have done that for class-monkey if it wasn't for the fact that sbt itself needs it.

**Comment by non** [comment]
Thanks for the pointers! I'll take a look and see what I can do.

**Comment by tunesmith** [comment]
Does this point to a possible resolution?  https://github.com/lihaoyi/scala-bench/blob/master/build.sbt

**Comment by non** [comment]
@tunesmith It turns out that `sbt-javaagent` seems to work pretty well. I've updated the README and am closing this out. Thanks to everyone for your help!
